services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/AnimalAllies.Web/Dockerfile
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy    
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=Admin123
    
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "animalAllies"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345890"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d animalAllies",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    
  minio:
    container_name: minio
    image: minio/minio
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3
  
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  rabbitmq_data:
  postgres-data:
  minio-data:
 
