services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/AnimalAllies.Web/Dockerfile
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy    
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "animalAllies"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345890"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d animalAllies",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    
  minio:
    container_name: minio
    image: minio/minio
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres-data:
  minio-data:
 