version: '3.8'  

services:
  fileservice:
    image: fileservice
    build:
      context: .
      dockerfile: src/FileService/Dockerfile

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  seq:
    image: datalust/seq:latest
    container_name: seq-file-service
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5345:5345"
      - "8085:80"

  minio:
    container_name: minio-file-service
    image: minio/minio
    ports:
      - "9007:9007"
      - "9009:9009"
    volumes:
      - minio-data:/data
    command: server --console-address ":9009" /data
    restart: always

volumes:
  minio-data: {}