# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: AnimalAlliesBackend

env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: |
          dotnet restore ./TelegramBotService/TelegramBotService.sln
          dotnet restore ./NotificationService/NotificationService.sln
          dotnet restore ./FileService/FileService.sln
          dotnet restore ./CacheInvalidatorService/CacheInvalidatorService.sln
          dotnet restore ./backend/backend.sln
          
      - name: Build
        run: |
          dotnet build ./TelegramBotService/TelegramBotService.sln --configuration Release --no-restore
          dotnet build ./NotificationService/NotificationService.sln --configuration Release --no-restore
          dotnet build ./FileService/FileService.sln --configuration Release --no-restore
          dotnet build ./CacheInvalidatorService/CacheInvalidatorService.sln --configuration Release --no-restore
          dotnet build ./backend/backend.sln --configuration Release --no-restore

      - name: Services_Tests
        run: |
          dotnet test ./TelegramBotService/TelegramBotService.sln --configuration Release --no-restore
          dotnet test ./NotificationService/NotificationService.sln --configuration Release --no-restore
          dotnet test ./FileService/FileService.sln --configuration Release --no-restore
          dotnet test ./CacheInvalidatorService/CacheInvalidatorService.sln --configuration Release --no-restore
          dotnet test ./backend/backend.sln --configuration Release --no-restore
         
